task:
  name: Builder AUR
  trigger_type: scheduled
  cron: "0 0 */5 * *"
  container:
    image: archlinux:latest
  matrix:
    - build: [
        microsoft-edge-dev-bin, postman-bin, geany-git, tor-browser-bin, wget2-git,
        earlyoom-git, slimjet, mpc-qt-git, spotify, insomnium, lightdm-settings, paru,
        wlogout, trizen, swww, sweet-theme-git, swaylock-effects, eww, mission-center,
        python-manimpango, python-clickgen, pfetch, pacseek, emote, bibata-cursor-theme,
        wf-config, mercury-browser-bin, aylurs-gtk-shell, vesktop
      ]
  steps:
    - makepkg_script:
        - pacman -Syu --noconfirm
        - pacman -S --noconfirm base-devel git
        - cd $CIRRUS_WORKING_DIR
        - git clone https://aur.archlinux.org/${CIRRUS_MATRIX_BUILD}.git
        - cd ${CIRRUS_MATRIX_BUILD}
        - makepkg -C --skippgpcheck
  artifacts:
    path: "**/*.zst"
    type: application/zstd