name: Builder
on:
  schedule:
    - cron: "0 0 */4 * *"
  workflow_dispatch:
jobs:
  Kernel:
    strategy:
      matrix:
        build: [
          linux-xanmod-lts, linux-xanmod,linux-xanmod-tt, linux-xanmod-custom, linux-xanmod
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@clang
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  CLANG:
    strategy:
      matrix:
        build: [
          zoom-system-qt, packettracer, thorium, libva-vdpau-driver, ffmpeg, libva, libvdpau, mesa, spotify
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@clang
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  GCC:
    strategy:
      matrix:
        build: [
          spotify-adblock-git, mpc-qt-git, github-desktop
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  AUR_CLANG:
    strategy:
      matrix:
        build: [
          microsoft-edge-dev-bin,postman-bin, aria2-git, zoom, whatsapp-for-linux, geany-git, tor-browser, wget2-git,
          appimagelauncher, earlyoom-git, slimjet
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
        with:
          repository: sarcasticadmin/empty-repo
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-clang
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  AUR_GCC:
    strategy:
      matrix:
        build: [
          visual-studio-code-bin, xampp, zramd, peazip-qt5, 7-zip, gtkcord4-git, joplin, resp-app, wine-ge-custom
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
        with:
          repository: sarcasticadmin/empty-repo
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}