name: Builder
on:
  push:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:



concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  Kernel:
    strategy:
      matrix:
        build: [
          linux-xanmod-custom
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@clang
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  CLANG:
    strategy:
      matrix:
        build: [
          packettracer, thorium,  mimalloc
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@clang
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  CLMUL:
    strategy:
      matrix:
        build: [
          resp-app
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@mpclmul
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  INTERNAL:
    needs: [CLANG, GCC, CLMUL]
    strategy:
      matrix:
        build: [
          libva-vdpau-driver, libva, libvdpau, mesa, aria2, nekoray
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@clang
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  GCC:
    strategy:
      matrix:
        build: [
          spotify-adblock-git
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  AUR_CLANG:
    strategy:
      matrix:
        build: [
          microsoft-edge-dev-bin, postman-bin, geany-git, tor-browser-bin, wget2-git,
          earlyoom-git, slimjet, mpc-qt-git, spotify, insomnium, lightdm-settings
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          repository: sarcasticadmin/empty-repo
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-clang
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  AUR_GCC:
    strategy:
      matrix:
        build: [
          visual-studio-code-bin, xampp, zramd, peazip-qt5, 7-zip, gtkcord4-git, joplin-electron, jdk-lts, 
          zulu-17-bin, appimagelauncher, jdk17-graalvm-ee-bin, premid-git, github-desktop, noisetorch, podman-desktop
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          repository: sarcasticadmin/empty-repo
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}