name: Builder Manual Sync
on:
  workflow_dispatch:

jobs:
  CLANG:
    strategy:
      matrix:
        build: [
          packettracer, thorium,  mimalloc, earlyoom
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-cached-tools: 'true'
          remove-large-packages: 'true'
          remove-codeql: 'true'
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          clanged: "y"
          clangedpflags: "y"
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  CLMUL:
    strategy:
      matrix:
        build: [
          resp-app
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          clanged: "y"
          clangedpflags: "y"
          namcapDisable: true
          cflags: "-mpclmul"
          cxxflags: "-mpclmul"
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  INTERNAL:
    strategy:
      matrix:
        build: [
          libva-vdpau-driver, libva, libvdpau, mesa, aria2
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-cached-tools: 'true'
          remove-large-packages: 'true'
          remove-codeql: 'true'
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          clanged: "y"
          officialRepo: "y"
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  EXPERIMENTAL:
    strategy:
      matrix:
        build: [
          aircrack-ng
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-cached-tools: 'true'
          remove-large-packages: 'true'
          remove-codeql: 'true'
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "temp"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  GCC:
    strategy:
      matrix:
        build: [
          spotify-adblock-git, zing
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "temp"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  TRIGGER_PUBLISH:
    if: ${{ always() }}
    needs: [EXPERIMENTAL, GCC, INTERNAL, CLANG, CLMUL]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: Create DB
