name: Builder
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:

  removing_all_tags:
    runs-on: ubuntu-latest
    steps: 
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_stable:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_custom:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-custom"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_lts:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-lts"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_edge:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-edge"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-cacule"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_spotify_adblock_git:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_spotify:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify"
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_cloudflared:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "cloudflared"
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true        
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
          
  build_xampp:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - run: ls -lR
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: 'xampp'
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true         
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  
  build_microsoft-edge-beta-bin:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - run: ls -lR
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"          
          pkgdir: 'microsoft-edge-dev-bin'
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true          
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_microsoft-edge-dev-bin:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - run: ls -lR
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"   
          pkgdir: 'microsoft-edge-beta-bin'
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true         
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_packet_tracer_cisco:
    needs: removing_all_tags
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git submodule update --recursive --remote
      - run: ls -lR
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: 'packettracer'
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
