name: Builder
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:

  CLANG_LTO:
    strategy:
      matrix:
        build: [aria2, bash, wget, wget2, linux-xanmod, linux-xanmod-custom,linux-xanmod-edge,linux-xanmod-lts,linux-xanmod-tt, packettracer, slimjet, spotify-adblock-git, cloudflared,microsoft-edge-dev-bin,microsoft-edge-beta-bin, spotify, yay]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@cpuv2
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: "*/*.zst"

  GCC:
    strategy:
      matrix:
        build: [xampp]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: "*/*.zst"


  create_db_file:
    needs: [GCC, CLANG_LTO]
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/download-artifact@v2.3.0
      - name: creating database
        run:  |
          repo-add arch-repository-jpratama7.db.tar
          repo-add arch-repository-jpratama7.db.tar *.pkg.tar.zst
          ls
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "./arch-repository-jpratama7.*"
          token: ${{ secrets.GITHUB_TOKEN }}