name: Builder
on:
  schedule:
    - cron: "0 0 */4 * *"
  workflow_dispatch:
jobs:

  CPUV2:
    strategy:
      matrix:
        build: [zoom-system-qt,linux-xanmod, linux-xanmod-custom,linux-xanmod-edge,linux-xanmod-tt, packettracer, slimjet, python]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@cpuv2
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  AUR_CPUV2:
    strategy:
      matrix:
        build: [microsoft-edge-dev-bin,microsoft-edge-beta-bin, spotify, wget2-git, aria2-git]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-cpuv2
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  AUR_GCC:
    strategy:
      matrix:
        build: [mpc-qt-git, cloudflared, xampp, pamac-aur, libpamac-aur, pamac-nosnap, libpamac-nosnap, whatsdesk-git]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  GCC:
    strategy:
      matrix:
        build: [linux-xanmod-lts, github-desktop]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@gcc
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  Original:
    strategy:
      matrix:
        build: [pypy38, spotify-adblock-git]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
