name: Builder
on:
  push:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:

  delete_all_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_stable:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_custom:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-custom"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_lts:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-lts"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_edge:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-edge"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule_uksm_cjktty:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule-uksm for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-cacule-uksm-cjktty"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-cacule"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_spotify_adblock_git:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.5
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
          aurDeps: "spotify"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_spotify:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_ungoogled_chromium:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "ungoogled-chromium"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_cloudflared:
    needs: [delete_all_tags]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "cloudflared"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

