name: Builder
on:
  push:
  workflow_dispatch:
jobs:

  build_xanmod_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_custom:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-custom"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_lts:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-lts"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_edge:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-edge"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule_uksm_cjktty:
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule-uksm for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-cacule-uksm-cjktty"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "app"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule:
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "linux-xanmod-cacule"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
          aurDeps: "spotify"

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: JPratama/arch-packages # defaults to current repo
          keep_latest: 0
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "app"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}