name: Builder AUR
on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:


jobs:
  AUR_CLANG:
    strategy:
      matrix:
        build: [
          microsoft-edge-dev-bin, postman-bin, geany-git, tor-browser-bin, aircrack-ng-git,
          slimjet, mpc-qt-git, spotify, insomnium, lightdm-settings, paru, jamesdsp, 
          wlogout, trizen, swww, sweet-theme-git, swaylock-effects, eww, mission-center,
          python-manimpango, python-clickgen, pfetch, pacseek, emote, bibata-cursor-theme,
          wf-config, mercury-browser-bin, aylurs-gtk-shell, vesktop, matugen-bin, asusctl,
          grimblast-git, gtklock, gtklock-userinfo-module, pywal-16-colors, sway-audio-idle-inhibit-git,
          libadwaita-without-adwaita-git, gtk-session-lock, hyprshade, waypaper, wallust-git,
          xdg-desktop-portal-hyprland-git, cava, zed-git, libva-nvidia-driver-git, sourcegit,
          slack-electron, waydroid, pwvucontrol, apple-music-desktop, windsurf,
          python-ufonormalizer, afdko
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-cached-tools: 'true'
          remove-large-packages: 'true'
          remove-codeql: 'true'
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          repository: sarcasticadmin/empty-repo
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
          clanged: "y"
          clangedpflags: "y"
          officialRepo: "y"
          ldflags: "-Wl,-z,nostart-stop-gc"
          rustcflags: "-C link-arg=-Wl,-z,nostart-stop-gc"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  Aylur:
    strategy:
      matrix:
        build: [
        libastal-git,
        libastal-4-git,
        libastal-apps-git,
        libastal-auth-git,
        libastal-battery-git,
        libastal-bluetooth-git,
        libastal-cava-git,
        libastal-greetd-git,
        libastal-hyprland-git,
        libastal-io-git,
        libastal-mpris-git,
        libastal-network-git,
        libastal-notifd-git,
        libastal-powerprofiles-git,
        libastal-river-git,
        libastal-tray-git,
        libastal-wireplumber-git,
        appmenu-glib-translator-git
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-cached-tools: 'true'
          remove-large-packages: 'true'
          remove-codeql: 'true'
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          repository: sarcasticadmin/empty-repo
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
          clanged: "y"
          clangedpflags: "y"
          officialRepo: "y"
          ldflags: "-Wl,-z,nostart-stop-gc"
          rustcflags: "-C link-arg=-Wl,-z,nostart-stop-gc"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  AUR_GCC:
    strategy:
      matrix:
        build: [
          visual-studio-code-bin, xampp, zramd, 7-zip, jdk-lts, jdk21-graalvm-ee-bin, wget2-git,
          zulu-17-bin, appimagelauncher, jdk17-graalvm-ee-bin, podman-desktop,
          yay, aws-cli-v2
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-cached-tools: 'true'
          remove-large-packages: 'true'
          remove-codeql: 'true'
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          repository: sarcasticadmin/empty-repo
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          maxJobs: "5"
          gccPFlags: "y"
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "temp"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  Proton:
    strategy:
      matrix:
        build: [
          proton-ge-custom, wine-ge-custom, lib32-lzo
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
        with:
          repository: sarcasticadmin/empty-repo
      - id: makepkg
        uses: JPratama7/pkgbuild-action@original
        with:
          maxJobs: "5"
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "temp"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


  TRIGGER_PUBLISH:
    if: ${{ always() }}
    needs: [AUR_CLANG, AUR_GCC, Aylur, Proton]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: Create DB
