name: Upload to github
on:
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:
jobs: 
  uploading_gitlab: 
    runs-on: ubuntu-latest
    steps: 
       
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOST }}              
      - run: |
            git clone git@gitlab.com:josepratama080/arch-repository.git
            rm -rf arch-repository/X86-64
            mkdir arch-repository/X86-64
      - run: ls -lR
      - run: |
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "${{ secrets.USERNAME }}"
      - uses: robinraju/release-downloader@v1.2
        with: 
          fileName: "*"
          latest: true
          out-file-path: arch-repository/X86-64
          repository: JPratama7/arch-builder
          tarBall: false
          zipBall: false
      - 
        run: |
            cd arch-repository
            git lfs install
            git lfs track "*.zst"
            git add .
            git commit -m 'add files'
            git push
