name: Upload to gitlab
on:
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:
jobs: 

  uploading_gitlab: 
    runs-on: ubuntu-latest
    steps: 
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOST }}              
      - run: |
            git clone git@gitlab.com:josepratama080/arch-repository.git
            git lfs fetch --all
            ls -lR
            rm -rf arch-repository/X86-64
            mkdir arch-repository/X86-64
      - run: ls -lR
      - run: |
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "${{ secrets.USERNAME }}"
      - uses: robinraju/release-downloader@v1.2
        with: 
          fileName: "*"
          latest: true
          out-file-path: arch-repository/X86-64
          repository: JPratama7/arch-builder
          tarBall: false
          zipBall: false
      - 
        run: |
            cd arch-repository
            #git lfs install
            #git lfs track "*.zst"
            git add .
            git commit -m 'add files'
            git push

  removing_all_tags:
    needs: uploading_gitlab
    runs-on: ubuntu-latest
    steps: 
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    
