name: Helper
on:
  workflow_dispatch:
jobs:
  arch_packages:
    strategy:
      matrix:
        build: [yay]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
        # with:
          # repository: h0tc0d3/arch-packages
      # - name : update submodule
        # run: git submodule update --recursive --remote
      # - name: remove +clang
        # run: |
          # cd ${{ matrix.build }} && sed -i 's/+clang//g' PKGBUILD
      - id: makepkg
        uses: JPratama7/pkgbuild-action@ok
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      # - name: Wait
      #   run: sleep 5m
      #   shell: bash
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

