name: Kernel
on:
  push:
    paths:
    - 'linux-lilium/*'
  workflow_dispatch:


concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  LLVM:
    strategy:
      matrix:
        build: [
          linux-lilium
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@clanged
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: '*/*.zst'
          token: ${{ secrets.GITHUB_TOKEN }}
  
  TRIGGER_PUBLISH:
    needs: [LLVM]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: Create DB
