name: Github Action Build PKGBUILD
on:
  push:
  workflow_dispatch:
jobs:

  build_xanmod_custom:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          pkgdir: 'kernel/linux-xanmod-custom'
          makepkgArgs: '--skippgpcheck'
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_lts:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          pkgdir: 'kernel/linux-xanmod-lts'
          makepkgArgs: '--skippgpcheck'
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_edge:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          pkgdir: 'kernel/linux-xanmod-edge'
          makepkgArgs: '--skippgpcheck'
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule_uksm_cjktty:
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule-uksm for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          pkgdir: 'kernel/linux-xanmod-cacule-uksm-cjktty'
          makepkgArgs: '--skippgpcheck'
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          pkgdir: 'app/slimjet'
          makepkgArgs: '--skippgpcheck'
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "app"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
