name: Github Action Build PKGBUILD
on:
  push:
  workflow_dispatch:
jobs:

  build_xanmod_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "kernel/linux-xanmod"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "kernel/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_custom:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "kernel/linux-xanmod-custom"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "kernel/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_lts:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "kernel/linux-xanmod-lts"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "kernel/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_edge:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "kernel/linux-xanmod-edge"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "kernel/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_xanmod_cacule_uksm_cjktty:
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule-uksm for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "kernel/linux-xanmod-cacule-uksm-cjktty"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "kernel"
          artifacts: "kernel/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.7
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "app/slimjet"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "app"
          artifacts: "app/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
