name: Create DB Manual
on:
  workflow_dispatch:
  
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create_aur_repository:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --needed aria2 base-devel

      - name: Wait for primary workflow to finish
        run: |
          while ! gh run list --workflow=Create DB\ Workflow --status=completed > /dev/null; do
            echo "Waiting for Create DB Workflow to complete..."
            sleep 30
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: "Downloading"
        run: |
          urls=$(curl https://github.com/JPratama7/arch-builder/releases/expanded_assets/latest -s|grep "/JPratama7/arch-builder/releases/download/latest/"|awk -F '"|"' '{print$2}')

          for i in ${urls[*]}; do 
              pkg=$(echo $i|awk -F '/' '{print$7}')
              echo Downloading $pkg
              aria2c -x 16 -s 16 https://github.com/$i
          done

      - name: "Download Older database"
        run: |
          urls=$(curl https://github.com/JPratama7/arch-builder/releases/expanded_assets/latest -s | grep "/JPratama7/arch-builder/releases/download/latest/" | grep jp7-arch | awk -F '"|"' '{print$2}')

          for i in ${urls[*]}; do 
              pkg=$(echo $i|awk -F '/' '{print$7}')
              echo Downloading $pkg
              aria2c -x 16 -s 16 https://github.com/$i
          done

      - name: creating database
        run:  |
          repo-add jp7-arch.db.tar *.pkg.tar.zst
          
      - name: upload files
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload database
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "jp7-arch.db,jp7-arch.db.tar,jp7-arch.db.tar.old,jp7-arch.files,jp7-arch.files.tar,jp7-arch.files.tar.old"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: "temp"
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}