name: Create DB
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:

  create_aur_repository:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: robinraju/release-downloader@v1.2
        with:
          repository: 'JPratama7/arch-builder'
          latest: true
          fileName: "*"
          tarBall: false
          zipBall: false
          out-file-path: ""
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - run: |
           rm arch-repository-jpratama7.*
      - name: creating database
        run:  |
          repo-add arch-repository-jpratama7.db.tar
          repo-add arch-repository-jpratama7.db.tar *.pkg.tar.zst
          ls
      - uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          re
          tag: "latest"
          artifacts: "./arch-repository-jpratama7.*"
          token: ${{ secrets.GITHUB_TOKEN }}