name: test
on:
  push:
  workflow_dispatch:
jobs:

  build_xanmod_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-custom for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: JPratama7/arch-pkgbuild-builder@main
        with:
          target: "pkgbuild"
          pkgname: "kernel/linux-xanmod-custom"
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "test"
          artifacts: "kernel/./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}