name: Toolchain
on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
jobs:
  LLVM:
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
      - id: makepkg
        uses: JPratama7/pkgbuild-action@toolchain
        with:
          pkgdir: "llvm-all"
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  aur-helper:
      runs-on: ubuntu-latest
      steps:
        - name: Build packages for arch
          uses: actions/checkout@v2.4.0
        - id: makepkg
          uses: JPratama7/pkgbuild-action@aur-gcc
          with:
            pkgdir: "yay"
            makepkgArgs: "--skippgpcheck"
        - name: Upload Artifact
          uses: ncipollo/release-action@v1.10.0
          with:
            allowUpdates: true
            tag: "latest"
            artifacts: "*/*.zst"
            token: ${{ secrets.GITHUB_TOKEN }}
