name: Toolchain
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  LLVM:
    strategy:
      matrix:
        build: [
          llvm-all, llvm-runtime
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@toolchain
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: '*/*.zst'
          token: ${{ secrets.GITHUB_TOKEN }}
  
  aur-helper:
      runs-on: ubuntu-latest
      steps:
        - name: Build packages for arch
          uses: actions/checkout@v3.5.3
        - id: makepkg
          uses: JPratama7/pkgbuild-action@aur-gcc
          with:
            pkgdir: "yay"
            makepkgArgs: "--skippgpcheck"
        - name: Upload Artifact
          uses: ncipollo/release-action@v1.12.0
          with:
            allowUpdates: true
            tag: "temp"
            artifacts: '*/*.zst'
            token: ${{ secrets.GITHUB_TOKEN }}

  weekly:
    strategy:
      matrix:
        build: [
          aircrack-ng
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.5.3
      - id: makepkg
        uses: JPratama7/pkgbuild-action@toolchain
        with:
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "temp"
          artifacts: '*/*.zst'
          token: ${{ secrets.GITHUB_TOKEN }}

  TRIGGER_PUBLISH:
    needs: [aur-helper, LLVM]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: Create DB
